/**
 * @fileoverview gRPC-Web generated client stub for UserSample
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: user_sample_command.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js')

var result_pb = require('./result_pb.js')
const proto = {};
proto.UserSample = require('./user_sample_command_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserSample.UserSampleCommandClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserSample.UserSampleCommandPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserSample.CreateSampleRequest,
 *   !proto.CommonResult>}
 */
const methodDescriptor_UserSampleCommand_CreateSample = new grpc.web.MethodDescriptor(
  '/UserSample.UserSampleCommand/CreateSample',
  grpc.web.MethodType.UNARY,
  proto.UserSample.CreateSampleRequest,
  result_pb.CommonResult,
  /**
   * @param {!proto.UserSample.CreateSampleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  result_pb.CommonResult.deserializeBinary
);


/**
 * @param {!proto.UserSample.CreateSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CommonResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CommonResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserSample.UserSampleCommandClient.prototype.createSample =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserSample.UserSampleCommand/CreateSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_CreateSample,
      callback);
};


/**
 * @param {!proto.UserSample.CreateSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CommonResult>}
 *     Promise that resolves to the response
 */
proto.UserSample.UserSampleCommandPromiseClient.prototype.createSample =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserSample.UserSampleCommand/CreateSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_CreateSample);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserSample.UpdateSampleRequest,
 *   !proto.CommonResult>}
 */
const methodDescriptor_UserSampleCommand_UpdateSample = new grpc.web.MethodDescriptor(
  '/UserSample.UserSampleCommand/UpdateSample',
  grpc.web.MethodType.UNARY,
  proto.UserSample.UpdateSampleRequest,
  result_pb.CommonResult,
  /**
   * @param {!proto.UserSample.UpdateSampleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  result_pb.CommonResult.deserializeBinary
);


/**
 * @param {!proto.UserSample.UpdateSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CommonResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CommonResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserSample.UserSampleCommandClient.prototype.updateSample =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserSample.UserSampleCommand/UpdateSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_UpdateSample,
      callback);
};


/**
 * @param {!proto.UserSample.UpdateSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CommonResult>}
 *     Promise that resolves to the response
 */
proto.UserSample.UserSampleCommandPromiseClient.prototype.updateSample =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserSample.UserSampleCommand/UpdateSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_UpdateSample);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserSample.DeleteSampleRequest,
 *   !proto.CommonResult>}
 */
const methodDescriptor_UserSampleCommand_DeleteSample = new grpc.web.MethodDescriptor(
  '/UserSample.UserSampleCommand/DeleteSample',
  grpc.web.MethodType.UNARY,
  proto.UserSample.DeleteSampleRequest,
  result_pb.CommonResult,
  /**
   * @param {!proto.UserSample.DeleteSampleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  result_pb.CommonResult.deserializeBinary
);


/**
 * @param {!proto.UserSample.DeleteSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CommonResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CommonResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserSample.UserSampleCommandClient.prototype.deleteSample =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserSample.UserSampleCommand/DeleteSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_DeleteSample,
      callback);
};


/**
 * @param {!proto.UserSample.DeleteSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CommonResult>}
 *     Promise that resolves to the response
 */
proto.UserSample.UserSampleCommandPromiseClient.prototype.deleteSample =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserSample.UserSampleCommand/DeleteSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleCommand_DeleteSample);
};


module.exports = proto.UserSample;

