/**
 * @fileoverview gRPC-Web generated client stub for UserSample
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: user_sample_query.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var result_pb = require('./result_pb.js')

var common_pb = require('./common_pb.js')

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js')
const proto = {};
proto.UserSample = require('./user_sample_query_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserSample.UserSampleQueryClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserSample.UserSampleQueryPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserSample.GetSampleRequest,
 *   !proto.CommonResult>}
 */
const methodDescriptor_UserSampleQuery_GetSample = new grpc.web.MethodDescriptor(
  '/UserSample.UserSampleQuery/GetSample',
  grpc.web.MethodType.UNARY,
  proto.UserSample.GetSampleRequest,
  result_pb.CommonResult,
  /**
   * @param {!proto.UserSample.GetSampleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  result_pb.CommonResult.deserializeBinary
);


/**
 * @param {!proto.UserSample.GetSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CommonResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CommonResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserSample.UserSampleQueryClient.prototype.getSample =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserSample.UserSampleQuery/GetSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleQuery_GetSample,
      callback);
};


/**
 * @param {!proto.UserSample.GetSampleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CommonResult>}
 *     Promise that resolves to the response
 */
proto.UserSample.UserSampleQueryPromiseClient.prototype.getSample =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserSample.UserSampleQuery/GetSample',
      request,
      metadata || {},
      methodDescriptor_UserSampleQuery_GetSample);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserSample.GetAllSamplesRequest,
 *   !proto.CommonResult>}
 */
const methodDescriptor_UserSampleQuery_GetAllSamples = new grpc.web.MethodDescriptor(
  '/UserSample.UserSampleQuery/GetAllSamples',
  grpc.web.MethodType.UNARY,
  proto.UserSample.GetAllSamplesRequest,
  result_pb.CommonResult,
  /**
   * @param {!proto.UserSample.GetAllSamplesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  result_pb.CommonResult.deserializeBinary
);


/**
 * @param {!proto.UserSample.GetAllSamplesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CommonResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CommonResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserSample.UserSampleQueryClient.prototype.getAllSamples =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserSample.UserSampleQuery/GetAllSamples',
      request,
      metadata || {},
      methodDescriptor_UserSampleQuery_GetAllSamples,
      callback);
};


/**
 * @param {!proto.UserSample.GetAllSamplesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CommonResult>}
 *     Promise that resolves to the response
 */
proto.UserSample.UserSampleQueryPromiseClient.prototype.getAllSamples =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserSample.UserSampleQuery/GetAllSamples',
      request,
      metadata || {},
      methodDescriptor_UserSampleQuery_GetAllSamples);
};


module.exports = proto.UserSample;

